// Generated by gencpp from file moveit_tutorial/add_collision.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIAL_MESSAGE_ADD_COLLISION_H
#define MOVEIT_TUTORIAL_MESSAGE_ADD_COLLISION_H

#include <ros/service_traits.h>


#include <moveit_tutorial/add_collisionRequest.h>
#include <moveit_tutorial/add_collisionResponse.h>


namespace moveit_tutorial
{

struct add_collision
{

typedef add_collisionRequest Request;
typedef add_collisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_collision
} // namespace moveit_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorial::add_collision > {
  static const char* value()
  {
    return "b380d5e794a5c8669b06015af1098b91";
  }

  static const char* value(const ::moveit_tutorial::add_collision&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorial::add_collision > {
  static const char* value()
  {
    return "moveit_tutorial/add_collision";
  }

  static const char* value(const ::moveit_tutorial::add_collision&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorial::add_collisionRequest> should match
// service_traits::MD5Sum< ::moveit_tutorial::add_collision >
template<>
struct MD5Sum< ::moveit_tutorial::add_collisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorial::add_collision >::value();
  }
  static const char* value(const ::moveit_tutorial::add_collisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorial::add_collisionRequest> should match
// service_traits::DataType< ::moveit_tutorial::add_collision >
template<>
struct DataType< ::moveit_tutorial::add_collisionRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorial::add_collision >::value();
  }
  static const char* value(const ::moveit_tutorial::add_collisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorial::add_collisionResponse> should match
// service_traits::MD5Sum< ::moveit_tutorial::add_collision >
template<>
struct MD5Sum< ::moveit_tutorial::add_collisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorial::add_collision >::value();
  }
  static const char* value(const ::moveit_tutorial::add_collisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorial::add_collisionResponse> should match
// service_traits::DataType< ::moveit_tutorial::add_collision >
template<>
struct DataType< ::moveit_tutorial::add_collisionResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorial::add_collision >::value();
  }
  static const char* value(const ::moveit_tutorial::add_collisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIAL_MESSAGE_ADD_COLLISION_H
