(cl:defpackage cw3_world_spawner-srv
  (:use )
  (:export
   "TASK1SERVICE"
   "<TASK1SERVICE-REQUEST>"
   "TASK1SERVICE-REQUEST"
   "<TASK1SERVICE-RESPONSE>"
   "TASK1SERVICE-RESPONSE"
   "TASK2SERVICE"
   "<TASK2SERVICE-REQUEST>"
   "TASK2SERVICE-REQUEST"
   "<TASK2SERVICE-RESPONSE>"
   "TASK2SERVICE-RESPONSE"
   "TASK3SERVICE"
   "<TASK3SERVICE-REQUEST>"
   "TASK3SERVICE-REQUEST"
   "<TASK3SERVICE-RESPONSE>"
   "TASK3SERVICE-RESPONSE"
   "TASKSETUP"
   "<TASKSETUP-REQUEST>"
   "TASKSETUP-REQUEST"
   "<TASKSETUP-RESPONSE>"
   "TASKSETUP-RESPONSE"
  ))

