(cl:defpackage cw3_team_14-srv
  (:use )
  (:export
   "EXAMPLE"
   "<EXAMPLE-REQUEST>"
   "EXAMPLE-REQUEST"
   "<EXAMPLE-RESPONSE>"
   "EXAMPLE-RESPONSE"
   "SET_ARM"
   "<SET_ARM-REQUEST>"
   "SET_ARM-REQUEST"
   "<SET_ARM-RESPONSE>"
   "SET_ARM-RESPONSE"
   "SET_GRIPPER"
   "<SET_GRIPPER-REQUEST>"
   "SET_GRIPPER-REQUEST"
   "<SET_GRIPPER-RESPONSE>"
   "SET_GRIPPER-RESPONSE"
  ))

