// Generated by gencpp from file cw3_team_14/set_arm.msg
// DO NOT EDIT!


#ifndef CW3_TEAM_14_MESSAGE_SET_ARM_H
#define CW3_TEAM_14_MESSAGE_SET_ARM_H

#include <ros/service_traits.h>


#include <cw3_team_14/set_armRequest.h>
#include <cw3_team_14/set_armResponse.h>


namespace cw3_team_14
{

struct set_arm
{

typedef set_armRequest Request;
typedef set_armResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_arm
} // namespace cw3_team_14


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw3_team_14::set_arm > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::cw3_team_14::set_arm&) { return value(); }
};

template<>
struct DataType< ::cw3_team_14::set_arm > {
  static const char* value()
  {
    return "cw3_team_14/set_arm";
  }

  static const char* value(const ::cw3_team_14::set_arm&) { return value(); }
};


// service_traits::MD5Sum< ::cw3_team_14::set_armRequest> should match
// service_traits::MD5Sum< ::cw3_team_14::set_arm >
template<>
struct MD5Sum< ::cw3_team_14::set_armRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_team_14::set_arm >::value();
  }
  static const char* value(const ::cw3_team_14::set_armRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_team_14::set_armRequest> should match
// service_traits::DataType< ::cw3_team_14::set_arm >
template<>
struct DataType< ::cw3_team_14::set_armRequest>
{
  static const char* value()
  {
    return DataType< ::cw3_team_14::set_arm >::value();
  }
  static const char* value(const ::cw3_team_14::set_armRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw3_team_14::set_armResponse> should match
// service_traits::MD5Sum< ::cw3_team_14::set_arm >
template<>
struct MD5Sum< ::cw3_team_14::set_armResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_team_14::set_arm >::value();
  }
  static const char* value(const ::cw3_team_14::set_armResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_team_14::set_armResponse> should match
// service_traits::DataType< ::cw3_team_14::set_arm >
template<>
struct DataType< ::cw3_team_14::set_armResponse>
{
  static const char* value()
  {
    return DataType< ::cw3_team_14::set_arm >::value();
  }
  static const char* value(const ::cw3_team_14::set_armResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW3_TEAM_14_MESSAGE_SET_ARM_H
