// Generated by gencpp from file cw3_team_14/set_gripper.msg
// DO NOT EDIT!


#ifndef CW3_TEAM_14_MESSAGE_SET_GRIPPER_H
#define CW3_TEAM_14_MESSAGE_SET_GRIPPER_H

#include <ros/service_traits.h>


#include <cw3_team_14/set_gripperRequest.h>
#include <cw3_team_14/set_gripperResponse.h>


namespace cw3_team_14
{

struct set_gripper
{

typedef set_gripperRequest Request;
typedef set_gripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_gripper
} // namespace cw3_team_14


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw3_team_14::set_gripper > {
  static const char* value()
  {
    return "a328c0db6d1f73db097d15f13b92a27a";
  }

  static const char* value(const ::cw3_team_14::set_gripper&) { return value(); }
};

template<>
struct DataType< ::cw3_team_14::set_gripper > {
  static const char* value()
  {
    return "cw3_team_14/set_gripper";
  }

  static const char* value(const ::cw3_team_14::set_gripper&) { return value(); }
};


// service_traits::MD5Sum< ::cw3_team_14::set_gripperRequest> should match
// service_traits::MD5Sum< ::cw3_team_14::set_gripper >
template<>
struct MD5Sum< ::cw3_team_14::set_gripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_team_14::set_gripper >::value();
  }
  static const char* value(const ::cw3_team_14::set_gripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_team_14::set_gripperRequest> should match
// service_traits::DataType< ::cw3_team_14::set_gripper >
template<>
struct DataType< ::cw3_team_14::set_gripperRequest>
{
  static const char* value()
  {
    return DataType< ::cw3_team_14::set_gripper >::value();
  }
  static const char* value(const ::cw3_team_14::set_gripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw3_team_14::set_gripperResponse> should match
// service_traits::MD5Sum< ::cw3_team_14::set_gripper >
template<>
struct MD5Sum< ::cw3_team_14::set_gripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_team_14::set_gripper >::value();
  }
  static const char* value(const ::cw3_team_14::set_gripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_team_14::set_gripperResponse> should match
// service_traits::DataType< ::cw3_team_14::set_gripper >
template<>
struct DataType< ::cw3_team_14::set_gripperResponse>
{
  static const char* value()
  {
    return DataType< ::cw3_team_14::set_gripper >::value();
  }
  static const char* value(const ::cw3_team_14::set_gripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW3_TEAM_14_MESSAGE_SET_GRIPPER_H
