// Generated by gencpp from file cw3_team_14/set_gripperRequest.msg
// DO NOT EDIT!


#ifndef CW3_TEAM_14_MESSAGE_SET_GRIPPERREQUEST_H
#define CW3_TEAM_14_MESSAGE_SET_GRIPPERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw3_team_14
{
template <class ContainerAllocator>
struct set_gripperRequest_
{
  typedef set_gripperRequest_<ContainerAllocator> Type;

  set_gripperRequest_()
    : finger_distance(0.0)  {
    }
  set_gripperRequest_(const ContainerAllocator& _alloc)
    : finger_distance(0.0)  {
  (void)_alloc;
    }



   typedef double _finger_distance_type;
  _finger_distance_type finger_distance;





  typedef boost::shared_ptr< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_gripperRequest_

typedef ::cw3_team_14::set_gripperRequest_<std::allocator<void> > set_gripperRequest;

typedef boost::shared_ptr< ::cw3_team_14::set_gripperRequest > set_gripperRequestPtr;
typedef boost::shared_ptr< ::cw3_team_14::set_gripperRequest const> set_gripperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw3_team_14::set_gripperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cw3_team_14::set_gripperRequest_<ContainerAllocator1> & lhs, const ::cw3_team_14::set_gripperRequest_<ContainerAllocator2> & rhs)
{
  return lhs.finger_distance == rhs.finger_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cw3_team_14::set_gripperRequest_<ContainerAllocator1> & lhs, const ::cw3_team_14::set_gripperRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cw3_team_14

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac00d77bd1463b7cd29c5d40226dac06";
  }

  static const char* value(const ::cw3_team_14::set_gripperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac00d77bd1463b7cULL;
  static const uint64_t static_value2 = 0xd29c5d40226dac06ULL;
};

template<class ContainerAllocator>
struct DataType< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw3_team_14/set_gripperRequest";
  }

  static const char* value(const ::cw3_team_14::set_gripperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 finger_distance\n"
;
  }

  static const char* value(const ::cw3_team_14::set_gripperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finger_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_gripperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw3_team_14::set_gripperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw3_team_14::set_gripperRequest_<ContainerAllocator>& v)
  {
    s << indent << "finger_distance: ";
    Printer<double>::stream(s, indent + "  ", v.finger_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW3_TEAM_14_MESSAGE_SET_GRIPPERREQUEST_H
