// Generated by gencpp from file cw3_world_spawner/Task3ServiceResponse.msg
// DO NOT EDIT!


#ifndef CW3_WORLD_SPAWNER_MESSAGE_TASK3SERVICERESPONSE_H
#define CW3_WORLD_SPAWNER_MESSAGE_TASK3SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw3_world_spawner
{
template <class ContainerAllocator>
struct Task3ServiceResponse_
{
  typedef Task3ServiceResponse_<ContainerAllocator> Type;

  Task3ServiceResponse_()
    : total_num_shapes(0)
    , num_most_common_shape(0)
    , most_common_shape_vector()  {
    }
  Task3ServiceResponse_(const ContainerAllocator& _alloc)
    : total_num_shapes(0)
    , num_most_common_shape(0)
    , most_common_shape_vector(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _total_num_shapes_type;
  _total_num_shapes_type total_num_shapes;

   typedef int64_t _num_most_common_shape_type;
  _num_most_common_shape_type num_most_common_shape;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _most_common_shape_vector_type;
  _most_common_shape_vector_type most_common_shape_vector;





  typedef boost::shared_ptr< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Task3ServiceResponse_

typedef ::cw3_world_spawner::Task3ServiceResponse_<std::allocator<void> > Task3ServiceResponse;

typedef boost::shared_ptr< ::cw3_world_spawner::Task3ServiceResponse > Task3ServiceResponsePtr;
typedef boost::shared_ptr< ::cw3_world_spawner::Task3ServiceResponse const> Task3ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator1> & lhs, const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.total_num_shapes == rhs.total_num_shapes &&
    lhs.num_most_common_shape == rhs.num_most_common_shape &&
    lhs.most_common_shape_vector == rhs.most_common_shape_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator1> & lhs, const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cw3_world_spawner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4cdcbf342ebe5d2a91b198b8ea6a615";
  }

  static const char* value(const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4cdcbf342ebe5d2ULL;
  static const uint64_t static_value2 = 0xa91b198b8ea6a615ULL;
};

template<class ContainerAllocator>
struct DataType< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw3_world_spawner/Task3ServiceResponse";
  }

  static const char* value(const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 total_num_shapes\n"
"int64 num_most_common_shape\n"
"int64[] most_common_shape_vector\n"
"\n"
;
  }

  static const char* value(const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_num_shapes);
      stream.next(m.num_most_common_shape);
      stream.next(m.most_common_shape_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task3ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw3_world_spawner::Task3ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "total_num_shapes: ";
    Printer<int64_t>::stream(s, indent + "  ", v.total_num_shapes);
    s << indent << "num_most_common_shape: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_most_common_shape);
    s << indent << "most_common_shape_vector[]" << std::endl;
    for (size_t i = 0; i < v.most_common_shape_vector.size(); ++i)
    {
      s << indent << "  most_common_shape_vector[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.most_common_shape_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW3_WORLD_SPAWNER_MESSAGE_TASK3SERVICERESPONSE_H
