// Generated by gencpp from file cw3_world_spawner/Task1Service.msg
// DO NOT EDIT!


#ifndef CW3_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H
#define CW3_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H

#include <ros/service_traits.h>


#include <cw3_world_spawner/Task1ServiceRequest.h>
#include <cw3_world_spawner/Task1ServiceResponse.h>


namespace cw3_world_spawner
{

struct Task1Service
{

typedef Task1ServiceRequest Request;
typedef Task1ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task1Service
} // namespace cw3_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw3_world_spawner::Task1Service > {
  static const char* value()
  {
    return "ee66ea1bcc1704a8551b6f7b84e9cf9e";
  }

  static const char* value(const ::cw3_world_spawner::Task1Service&) { return value(); }
};

template<>
struct DataType< ::cw3_world_spawner::Task1Service > {
  static const char* value()
  {
    return "cw3_world_spawner/Task1Service";
  }

  static const char* value(const ::cw3_world_spawner::Task1Service&) { return value(); }
};


// service_traits::MD5Sum< ::cw3_world_spawner::Task1ServiceRequest> should match
// service_traits::MD5Sum< ::cw3_world_spawner::Task1Service >
template<>
struct MD5Sum< ::cw3_world_spawner::Task1ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw3_world_spawner::Task1ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_world_spawner::Task1ServiceRequest> should match
// service_traits::DataType< ::cw3_world_spawner::Task1Service >
template<>
struct DataType< ::cw3_world_spawner::Task1ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cw3_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw3_world_spawner::Task1ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw3_world_spawner::Task1ServiceResponse> should match
// service_traits::MD5Sum< ::cw3_world_spawner::Task1Service >
template<>
struct MD5Sum< ::cw3_world_spawner::Task1ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw3_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw3_world_spawner::Task1ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw3_world_spawner::Task1ServiceResponse> should match
// service_traits::DataType< ::cw3_world_spawner::Task1Service >
template<>
struct DataType< ::cw3_world_spawner::Task1ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cw3_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw3_world_spawner::Task1ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW3_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H
