// Generated by gencpp from file cw3_world_spawner/Task2ServiceResponse.msg
// DO NOT EDIT!


#ifndef CW3_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H
#define CW3_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw3_world_spawner
{
template <class ContainerAllocator>
struct Task2ServiceResponse_
{
  typedef Task2ServiceResponse_<ContainerAllocator> Type;

  Task2ServiceResponse_()
    : mystery_object_num(0)  {
    }
  Task2ServiceResponse_(const ContainerAllocator& _alloc)
    : mystery_object_num(0)  {
  (void)_alloc;
    }



   typedef int64_t _mystery_object_num_type;
  _mystery_object_num_type mystery_object_num;





  typedef boost::shared_ptr< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Task2ServiceResponse_

typedef ::cw3_world_spawner::Task2ServiceResponse_<std::allocator<void> > Task2ServiceResponse;

typedef boost::shared_ptr< ::cw3_world_spawner::Task2ServiceResponse > Task2ServiceResponsePtr;
typedef boost::shared_ptr< ::cw3_world_spawner::Task2ServiceResponse const> Task2ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator1> & lhs, const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mystery_object_num == rhs.mystery_object_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator1> & lhs, const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cw3_world_spawner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b1e7915ca008eed2a8644edc0612ba6";
  }

  static const char* value(const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b1e7915ca008eedULL;
  static const uint64_t static_value2 = 0x2a8644edc0612ba6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw3_world_spawner/Task2ServiceResponse";
  }

  static const char* value(const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mystery_object_num\n"
"\n"
;
  }

  static const char* value(const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mystery_object_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task2ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw3_world_spawner::Task2ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "mystery_object_num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mystery_object_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW3_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H
