// Generated by gencpp from file moveit_solution/pick.msg
// DO NOT EDIT!


#ifndef MOVEIT_SOLUTION_MESSAGE_PICK_H
#define MOVEIT_SOLUTION_MESSAGE_PICK_H

#include <ros/service_traits.h>


#include <moveit_solution/pickRequest.h>
#include <moveit_solution/pickResponse.h>


namespace moveit_solution
{

struct pick
{

typedef pickRequest Request;
typedef pickResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pick
} // namespace moveit_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_solution::pick > {
  static const char* value()
  {
    return "24f5679e0a52d4e75d20787acf70c895";
  }

  static const char* value(const ::moveit_solution::pick&) { return value(); }
};

template<>
struct DataType< ::moveit_solution::pick > {
  static const char* value()
  {
    return "moveit_solution/pick";
  }

  static const char* value(const ::moveit_solution::pick&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_solution::pickRequest> should match
// service_traits::MD5Sum< ::moveit_solution::pick >
template<>
struct MD5Sum< ::moveit_solution::pickRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::pick >::value();
  }
  static const char* value(const ::moveit_solution::pickRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::pickRequest> should match
// service_traits::DataType< ::moveit_solution::pick >
template<>
struct DataType< ::moveit_solution::pickRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::pick >::value();
  }
  static const char* value(const ::moveit_solution::pickRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_solution::pickResponse> should match
// service_traits::MD5Sum< ::moveit_solution::pick >
template<>
struct MD5Sum< ::moveit_solution::pickResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::pick >::value();
  }
  static const char* value(const ::moveit_solution::pickResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::pickResponse> should match
// service_traits::DataType< ::moveit_solution::pick >
template<>
struct DataType< ::moveit_solution::pickResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::pick >::value();
  }
  static const char* value(const ::moveit_solution::pickResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_SOLUTION_MESSAGE_PICK_H
