// Generated by gencpp from file moveit_solution/remove_collisionRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISIONREQUEST_H
#define MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_solution
{
template <class ContainerAllocator>
struct remove_collisionRequest_
{
  typedef remove_collisionRequest_<ContainerAllocator> Type;

  remove_collisionRequest_()
    : object_name()  {
    }
  remove_collisionRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct remove_collisionRequest_

typedef ::moveit_solution::remove_collisionRequest_<std::allocator<void> > remove_collisionRequest;

typedef boost::shared_ptr< ::moveit_solution::remove_collisionRequest > remove_collisionRequestPtr;
typedef boost::shared_ptr< ::moveit_solution::remove_collisionRequest const> remove_collisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_solution::remove_collisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_solution::remove_collisionRequest_<ContainerAllocator1> & lhs, const ::moveit_solution::remove_collisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_solution::remove_collisionRequest_<ContainerAllocator1> & lhs, const ::moveit_solution::remove_collisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::moveit_solution::remove_collisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_solution/remove_collisionRequest";
  }

  static const char* value(const ::moveit_solution::remove_collisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n"
;
  }

  static const char* value(const ::moveit_solution::remove_collisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remove_collisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_solution::remove_collisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_solution::remove_collisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISIONREQUEST_H
