// Generated by gencpp from file moveit_solution/remove_collision.msg
// DO NOT EDIT!


#ifndef MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISION_H
#define MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISION_H

#include <ros/service_traits.h>


#include <moveit_solution/remove_collisionRequest.h>
#include <moveit_solution/remove_collisionResponse.h>


namespace moveit_solution
{

struct remove_collision
{

typedef remove_collisionRequest Request;
typedef remove_collisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct remove_collision
} // namespace moveit_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_solution::remove_collision > {
  static const char* value()
  {
    return "bc93e0d7ed716275a8d9336d083ffb50";
  }

  static const char* value(const ::moveit_solution::remove_collision&) { return value(); }
};

template<>
struct DataType< ::moveit_solution::remove_collision > {
  static const char* value()
  {
    return "moveit_solution/remove_collision";
  }

  static const char* value(const ::moveit_solution::remove_collision&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_solution::remove_collisionRequest> should match
// service_traits::MD5Sum< ::moveit_solution::remove_collision >
template<>
struct MD5Sum< ::moveit_solution::remove_collisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::remove_collision >::value();
  }
  static const char* value(const ::moveit_solution::remove_collisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::remove_collisionRequest> should match
// service_traits::DataType< ::moveit_solution::remove_collision >
template<>
struct DataType< ::moveit_solution::remove_collisionRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::remove_collision >::value();
  }
  static const char* value(const ::moveit_solution::remove_collisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_solution::remove_collisionResponse> should match
// service_traits::MD5Sum< ::moveit_solution::remove_collision >
template<>
struct MD5Sum< ::moveit_solution::remove_collisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::remove_collision >::value();
  }
  static const char* value(const ::moveit_solution::remove_collisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::remove_collisionResponse> should match
// service_traits::DataType< ::moveit_solution::remove_collision >
template<>
struct DataType< ::moveit_solution::remove_collisionResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::remove_collision >::value();
  }
  static const char* value(const ::moveit_solution::remove_collisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_SOLUTION_MESSAGE_REMOVE_COLLISION_H
