// Generated by gencpp from file moveit_solution/set_gripper.msg
// DO NOT EDIT!


#ifndef MOVEIT_SOLUTION_MESSAGE_SET_GRIPPER_H
#define MOVEIT_SOLUTION_MESSAGE_SET_GRIPPER_H

#include <ros/service_traits.h>


#include <moveit_solution/set_gripperRequest.h>
#include <moveit_solution/set_gripperResponse.h>


namespace moveit_solution
{

struct set_gripper
{

typedef set_gripperRequest Request;
typedef set_gripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_gripper
} // namespace moveit_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_solution::set_gripper > {
  static const char* value()
  {
    return "a328c0db6d1f73db097d15f13b92a27a";
  }

  static const char* value(const ::moveit_solution::set_gripper&) { return value(); }
};

template<>
struct DataType< ::moveit_solution::set_gripper > {
  static const char* value()
  {
    return "moveit_solution/set_gripper";
  }

  static const char* value(const ::moveit_solution::set_gripper&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_solution::set_gripperRequest> should match
// service_traits::MD5Sum< ::moveit_solution::set_gripper >
template<>
struct MD5Sum< ::moveit_solution::set_gripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::set_gripper >::value();
  }
  static const char* value(const ::moveit_solution::set_gripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::set_gripperRequest> should match
// service_traits::DataType< ::moveit_solution::set_gripper >
template<>
struct DataType< ::moveit_solution::set_gripperRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::set_gripper >::value();
  }
  static const char* value(const ::moveit_solution::set_gripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_solution::set_gripperResponse> should match
// service_traits::MD5Sum< ::moveit_solution::set_gripper >
template<>
struct MD5Sum< ::moveit_solution::set_gripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_solution::set_gripper >::value();
  }
  static const char* value(const ::moveit_solution::set_gripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_solution::set_gripperResponse> should match
// service_traits::DataType< ::moveit_solution::set_gripper >
template<>
struct DataType< ::moveit_solution::set_gripperResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_solution::set_gripper >::value();
  }
  static const char* value(const ::moveit_solution::set_gripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_SOLUTION_MESSAGE_SET_GRIPPER_H
